platform :ios, '11.0'
use_frameworks!
target 'BLEWifiProvisioning' do
  #use_modular_headers!
  pod 'Alertift'
  pod 'AmazonFreeRTOS', :path => '../../'
  pod 'AWSIoT'
  pod 'LicensePlist'
  pod 'SwiftFormat/CLI'
  pod 'SwiftLint'
end

